import { createHash } from "crypto";
import yaml from "js-yaml";
import pc from "picocolors";
import fs from "fs";
import { genSchemes, summary } from "./generator";
import path from "path";

interface Cache {
  hash: string;
  timestamp: number;
  url: string;
  baseUrl: string;
}
export const writeCache = (path: string, cache: Cache): void => {
  try {
    fs.writeFileSync(path, JSON.stringify(cache, null, 2));
  } catch (error) {
    console.warn(pc.yellow(`[openapi-ts] Failed to write cache file at "${path}": ${error}`));
  }
}

export const extractBaseUrl = (urlString: string): string => {
  const urlObj = new URL(urlString);
  return `${urlObj.protocol}//${urlObj.host}`;
};

/**
 * 计算内容的 hash 值
 */
export const calculateHash = (content: string): string => {
  return createHash('sha256').update(content).digest('hex');
};

interface GenerateOptions {
  url: string;
  baseUrl: string;
  outputDir: string;
  enableCache: boolean;
  skipTimeout: number;
}
export async function generate(options: GenerateOptions): Promise<void> {
  const {
    url,
    baseUrl,
    outputDir,
    enableCache,
    skipTimeout,
  } = options;

  const isYaml = url.endsWith('.yaml') || url.endsWith('.yml');

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch OpenAPI spec: ${response.status} ${response.statusText}`);
  }
  const specText = await response.text();
  const specHash = calculateHash(specText);
  // 解析 OpenAPI spec
  const contentType = response.headers.get('content-type') || '';
  const shouldParseAsYaml = contentType.includes('yaml') || 
                            contentType.includes('yml') || 
                            isYaml;
  
  let openapi: any;
  try {
    // 根据检测结果解析
    if (shouldParseAsYaml) {
      console.log(pc.dim('[openapi-ts] Parsing as YAML format'));
      openapi = yaml.load(specText);
    } else {
      console.log(pc.dim('[openapi-ts] Parsing as JSON format'));
      openapi = JSON.parse(specText);
    }
  } catch (parseError) {
    console.log(pc.yellow(`[openapi-ts] Failed to parse as ${shouldParseAsYaml ? 'YAML' : 'JSON'}, trying alternative format...`));
    try {
      openapi = shouldParseAsYaml ? JSON.parse(specText) : yaml.load(specText);
    } catch (fallbackError) {
      throw new Error(`Failed to parse OpenAPI spec: ${parseError}`);
    }
  }

  const schemes = openapi.components?.schemas || {};
  const paths = openapi.paths || {};
  const servers: string[] = (openapi.servers || []).map((server: any) => server.url);
  
  // 生成 schemes.ts
  fs.writeFileSync(
    path.join(outputDir, 'schemes.ts'),
    `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
    genSchemes(schemes)
  );
  
  // 生成 index.ts
  fs.writeFileSync(
    path.join(outputDir, 'index.ts'),
    `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
    summary(paths, baseUrl, schemes, servers)
  );
  
  console.log(pc.green(`[openapi-ts] Generated ${pc.bold(outputDir + '/schemes.ts')} and ${pc.bold(outputDir + '/index.ts')}`));
  
  if (enableCache) {
    const cachePath = path.join(outputDir, '.openapi-cache.json');
    writeCache(cachePath, {
      hash: specHash,
      timestamp: Date.now(),
      url,
      baseUrl,
    });
    console.log(pc.dim(`[openapi-ts] Cache file written to ${cachePath}`));
  }
}