import { createHash } from "crypto";
import yaml from "js-yaml";
import pc from "picocolors";
import fs from "fs";
import { genSchemes, summary } from "./generator";
import path from "path";

export interface Cache {
  hash: string;
  timestamp: number;
  url: string;
  baseUrl: string;
}

export interface Logger {
  info: (msg: string) => void;
  warn: (msg: string) => void;
  error: (msg: string) => void;
  dim: (msg: string) => void;
}

export async function performGeneration(options: {
  url: string;
  baseUrl: string;
  outputDir: string;
  enableCache: boolean;
  skipTimeout: number;
  force?: boolean;
  logger: Logger;
  readCache: (cachePath: string) => Cache | null;
  writeCache: (cachePath: string, hash: string) => void;
}) {
  const { url, baseUrl, outputDir, enableCache, skipTimeout, force = false, logger, readCache, writeCache } = options;

  const outputPath = path.resolve(process.cwd(), outputDir);
  if (!fs.existsSync(outputPath)) {
    fs.mkdirSync(outputPath, { recursive: true });
  }
  const cachePath = path.join(outputPath, '.openapi-cache.json');

  if (skipTimeout > 0 && enableCache && !force) {
    const cache = readCache(cachePath);
    if (cache && cache.url === url && cache.baseUrl === baseUrl && (Date.now() - cache.timestamp) < skipTimeout) {
      logger.info(pc.green(`[openapi-ts] Skip timeout active, skipping generation (last generated: ${new Date(cache.timestamp).toLocaleString()})`));
      return;
    }
  }

  let specText: string;
  const isLocalFile = !url.startsWith('http://') && !url.startsWith('https://');

  if (isLocalFile) {
    logger.dim(`[openapi-ts] Reading local spec file: ${url}`);
    const filePath = path.resolve(process.cwd(), url);
    if (!fs.existsSync(filePath)) {
      throw new Error(`Local spec file not found at: ${filePath}`);
    }
    specText = fs.readFileSync(filePath, 'utf-8');
  } else {
    logger.dim(`[openapi-ts] Fetching OpenAPI spec from ${pc.dim(url)}`);
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch OpenAPI spec: ${response.status} ${response.statusText}`);
    }
    specText = await response.text();
  }

  const specHash = calculateHash(specText);

  if (enableCache && !force) {
    const cache = readCache(cachePath);
    if (cache && cache.hash === specHash && cache.baseUrl === baseUrl && cache.url === url) {
      const schemesPath = path.join(outputPath, 'schemes.ts');
      const indexPath = path.join(outputPath, 'index.ts');
      if (fs.existsSync(schemesPath) && fs.existsSync(indexPath)) {
        logger.info(pc.green(`[openapi-ts] Cache hit, skipping generation (hash: ${pc.dim(specHash.slice(0, 8))})`));
        return;
      } else {
        logger.warn(pc.yellow(`[openapi-ts] Cache found but generated files missing, regenerating...`));
      }
    }
  }

  const isYaml = url.endsWith('.yaml') || url.endsWith('.yml');
  let openapi: any;
  try {
    if (isYaml) {
      logger.dim('[openapi-ts] Parsing as YAML format');
      openapi = yaml.load(specText);
    } else {
      logger.dim('[openapi-ts] Parsing as JSON format');
      openapi = JSON.parse(specText);
    }
  } catch (parseError) {
    logger.warn(pc.yellow(`[openapi-ts] Failed to parse as ${isYaml ? 'YAML' : 'JSON'}, trying alternative format...`));
    try {
      openapi = isYaml ? JSON.parse(specText) : yaml.load(specText);
    } catch (fallbackError) {
      throw new Error(`Failed to parse OpenAPI spec: ${parseError}`);
    }
  }

  const schemes = openapi.components?.schemas || {};

  fs.writeFileSync(
    path.join(outputPath, 'schemes.ts'),
    `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
    genSchemes(schemes, openapi)
  );
  
  fs.writeFileSync(
    path.join(outputPath, 'index.ts'),
    `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
    summary(openapi, baseUrl)
  );
  
  logger.info(pc.green(`[openapi-ts] Generated ${pc.bold(outputDir + '/schemes.ts')} and ${pc.bold(outputDir + '/index.ts')}`));
  
  if (enableCache) {
    writeCache(cachePath, specHash);
  }
}


export const extractBaseUrl = (urlString: string): string => {
  const urlObj = new URL(urlString);
  return `${urlObj.protocol}//${urlObj.host}`;
};

export const calculateHash = (content: string): string => {
  return createHash('sha256').update(content).digest('hex');
};

interface GenerateOptions {
  url: string;
  baseUrl: string;
  outputDir: string;
  enableCache: boolean;
  skipTimeout: number;
  force?: boolean;
}

export async function generate(options: GenerateOptions): Promise<void> {
  const cliLogger: Logger = {
    info: console.log,
    warn: console.warn,
    error: console.error,
    dim: (msg: string) => console.log(pc.dim(msg)),
  };

  const readCliCache = (cachePath: string): Cache | null => {
    if (fs.existsSync(cachePath)) {
      return JSON.parse(fs.readFileSync(cachePath, 'utf-8'));
    }
    return null;
  };

  const writeCliCache = (cachePath: string, hash: string): void => {
    try {
      const cache: Cache = {
        hash,
        timestamp: Date.now(),
        url: options.url,
        baseUrl: options.baseUrl,
      };
      fs.writeFileSync(cachePath, JSON.stringify(cache, null, 2));
      cliLogger.dim(`[openapi-ts] Cache file written to ${cachePath}`);
    } catch (error) {
      cliLogger.warn(`[openapi-ts] Failed to write cache file at "${cachePath}": ${error}`);
    }
  };

  try {
    await performGeneration({
      ...options,
      logger: cliLogger,
      readCache: readCliCache,
      writeCache: writeCliCache,
    });
  } catch (error) {
    cliLogger.error(pc.red(`[openapi-ts] Failed to generate types: ${error}`));
  }
}

/**
 * Resolves a JSON Pointer reference within an OpenAPI document.
 * Handles URI-encoded characters ~1 for / and ~0 for ~.
 * @param refPath The reference path (e.g., "#/components/parameters/MyParam").
 * @param openapi The entire OpenAPI document object.
 * @returns The resolved component object, or null if not found.
 */
export function resolveRef(refPath: string, openapi: any): any {
  if (!refPath || !refPath.startsWith('#/')) {
    return null;
  }

  const parts = refPath.substring(2).split('/');
  let current = openapi;

  for (const part of parts) {
    if (typeof current !== 'object' || current === null) {
      return null;
    }
    const decodedPart = part.replace(/~1/g, '/').replace(/~0/g, '~');
    if (!(decodedPart in current)) {
      return null;
    }
    current = current[decodedPart];
  }

  return current;
}