import { type Plugin } from 'vite';
import fs from 'fs';
import path from 'path';
import pc from 'picocolors';
import { genSchemes, summary } from './generator';

export interface PluginOptions {
  /** OpenAPI specification URL */
  url: string;
  /** API base URL for the generated client */
  baseUrl?: string;
  /** Output directory relative to project root */
  outputDir?: string;
}

/**
 * Vite plugin to generate TypeScript types and API client from OpenAPI specification
 */
export default function openapiPlugin(options: PluginOptions): Plugin {
  const {
    url,
    outputDir = 'src/openapi'
  } = options;

  // 从 URL 中提取 baseUrl (协议 + 域名 + 端口)
  const extractBaseUrl = (urlString: string): string => {
    try {
      const urlObj = new URL(urlString);
      return `${urlObj.protocol}//${urlObj.host}`;
    } catch (error) {
      console.warn(pc.yellow(`[openapi-ts] Failed to extract baseUrl from URL "${urlString}", using default: http://localhost:8080`));
      return 'http://localhost:8080';
    }
  };

  const baseUrl = options.baseUrl ?? extractBaseUrl(url);

  return {
    name: 'vite-plugin-openapi-ts',
    
    async buildStart() {
      try {
        this.info(pc.cyan(`[openapi-ts] Fetching OpenAPI spec from ${pc.dim(url)}`));
        
        const openapi: any = await fetch(url).then(res => {
          if (!res.ok) {
            throw new Error(`Failed to fetch OpenAPI spec: ${res.status} ${res.statusText}`);
          }
          return res.json();
        });
        
        const schemes = openapi.components?.schemas || {};
        const paths = openapi.paths || {};
        const servers: string[] = (openapi.servers || []).map((server: any) => server.url);
        
        // 确保输出目录存在
        const outputPath = path.resolve(process.cwd(), outputDir);
        if (!fs.existsSync(outputPath)) {
          fs.mkdirSync(outputPath, { recursive: true });
        }
        
        // 生成 schemes.ts
        fs.writeFileSync(
          path.join(outputPath, 'schemes.ts'),
          `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
          genSchemes(schemes)
        );
        
        // 生成 index.ts
        fs.writeFileSync(
          path.join(outputPath, 'index.ts'),
          `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
          summary(paths, baseUrl, schemes, servers)
        );
        
        this.info(pc.green(`[openapi-ts] Generated ${pc.bold(outputDir + '/schemes.ts')} and ${pc.bold(outputDir + '/index.ts')}`));
        
      } catch (error) {
        this.error(pc.red(`[openapi-ts] Failed to generate types: ${error}`));
        throw error;
      }
    }
  };
}

// 命名导出
export { openapiPlugin };
