import { type Plugin } from 'vite';
import fs from 'fs';
import path from 'path';
import pc from 'picocolors';
import yaml from 'js-yaml';
import { genSchemes, summary } from './generator';

export interface PluginOptions {
  /** OpenAPI specification URL (supports both JSON and YAML formats) */
  url: string;
  /** API base URL for the generated client */
  baseUrl?: string;
  /** Output directory relative to project root */
  outputDir?: string;
}

/**
 * Vite plugin to generate TypeScript types and API client from OpenAPI specification
 */
export default function openapiPlugin(options: PluginOptions): Plugin {
  const {
    url,
    outputDir = 'src/openapi'
  } = options;

  // 从 URL 中提取 baseUrl (协议 + 域名 + 端口)
  const extractBaseUrl = (urlString: string): string => {
    try {
      const urlObj = new URL(urlString);
      return `${urlObj.protocol}//${urlObj.host}`;
    } catch (error) {
      console.warn(pc.yellow(`[openapi-ts] Failed to extract baseUrl from URL "${urlString}", using default: http://localhost:8080`));
      return 'http://localhost:8080';
    }
  };

  const baseUrl = options.baseUrl ?? extractBaseUrl(url);

  return {
    name: 'vite-plugin-openapi-ts',
    
    async buildStart() {
      try {
        this.info(pc.cyan(`[openapi-ts] Fetching OpenAPI spec from ${pc.dim(url)}`));
        
        // 检测是否为 YAML 格式
        const isYaml = url.endsWith('.yaml') || url.endsWith('.yml');
        
        const openapi: any = await fetch(url).then(async res => {
          if (!res.ok) {
            throw new Error(`Failed to fetch OpenAPI spec: ${res.status} ${res.statusText}`);
          }
          
          const text = await res.text();
          const contentType = res.headers.get('content-type') || '';
          
          // 优先使用 Content-Type，其次使用 URL 扩展名
          const shouldParseAsYaml = contentType.includes('yaml') || 
                                    contentType.includes('yml') || 
                                    isYaml;
          
          try {
            // 根据检测结果解析
            if (shouldParseAsYaml) {
              this.info(pc.dim('[openapi-ts] Parsing as YAML format'));
              return yaml.load(text);
            } else {
              this.info(pc.dim('[openapi-ts] Parsing as JSON format'));
              return JSON.parse(text);
            }
          } catch (parseError) {
            // 如果解析失败，尝试另一种格式（智能回退）
            this.warn(pc.yellow(`[openapi-ts] Failed to parse as ${shouldParseAsYaml ? 'YAML' : 'JSON'}, trying alternative format...`));
            try {
              return shouldParseAsYaml ? JSON.parse(text) : yaml.load(text);
            } catch (fallbackError) {
              throw new Error(`Failed to parse OpenAPI spec: ${parseError}`);
            }
          }
        });
        
        const schemes = openapi.components?.schemas || {};
        const paths = openapi.paths || {};
        const servers: string[] = (openapi.servers || []).map((server: any) => server.url);
        
        // 确保输出目录存在
        const outputPath = path.resolve(process.cwd(), outputDir);
        if (!fs.existsSync(outputPath)) {
          fs.mkdirSync(outputPath, { recursive: true });
        }
        
        // 生成 schemes.ts
        fs.writeFileSync(
          path.join(outputPath, 'schemes.ts'),
          `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
          genSchemes(schemes)
        );
        
        // 生成 index.ts
        fs.writeFileSync(
          path.join(outputPath, 'index.ts'),
          `// Auto-generated by vite-plugin-openapi-ts\n// Do not edit this file manually\n\n` +
          summary(paths, baseUrl, schemes, servers)
        );
        
        this.info(pc.green(`[openapi-ts] Generated ${pc.bold(outputDir + '/schemes.ts')} and ${pc.bold(outputDir + '/index.ts')}`));
        
      } catch (error) {
        this.error(pc.red(`[openapi-ts] Failed to generate types: ${error}`));
        throw error;
      }
    }
  };
}

// 命名导出
export { openapiPlugin };
